// Board-aware Scrabble move generation (Appel & Jacobson style).
//
// Horizontal plays are generated directly; vertical plays are generated by
// transposing the board, running the same horizontal generator, then mapping
// coordinates back. The premium-square layout is transpose-symmetric, so scores
// computed on the transposed board are correct for the real board.

import {
  BOARD_SIZE,
  BLANK,
  CENTER,
  letterValue,
  letterMultiplier,
  premiumAt,
  wordMultiplier,
} from "./board";
import type { Dictionary } from "./dictionary";

export interface Placement {
  row: number;
  col: number;
  letter: string;
  blank: boolean;
}

export interface Move {
  word: string;
  row: number; // start of the main word
  col: number;
  dir: "H" | "V";
  placements: Placement[];
  score: number;
}

const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

interface CrossCheck {
  allowed: Set<string> | null; // null means no constraint
  score: number; // sum of face values of the existing perpendicular neighbours
  exists: boolean;
}

function isFilled(board: string[][], r: number, c: number): boolean {
  return (
    r >= 0 &&
    r < BOARD_SIZE &&
    c >= 0 &&
    c < BOARD_SIZE &&
    board[r][c] !== ""
  );
}

// For each empty square, which letters can be placed there without breaking the
// perpendicular (vertical, in this orientation) word, plus that word's score.
function computeCrossChecks(
  board: string[][],
  dict: Dictionary
): CrossCheck[][] {
  const cross: CrossCheck[][] = Array.from({ length: BOARD_SIZE }, () =>
    Array.from({ length: BOARD_SIZE }, () => ({
      allowed: null as Set<string> | null,
      score: 0,
      exists: false,
    }))
  );

  for (let r = 0; r < BOARD_SIZE; r++) {
    for (let c = 0; c < BOARD_SIZE; c++) {
      if (board[r][c] !== "") continue;

      let up = "";
      let rr = r - 1;
      while (rr >= 0 && board[rr][c] !== "") {
        up = board[rr][c] + up;
        rr--;
      }
      let down = "";
      rr = r + 1;
      while (rr < BOARD_SIZE && board[rr][c] !== "") {
        down += board[rr][c];
        rr++;
      }

      if (up === "" && down === "") continue;

      const allowed = new Set<string>();
      for (const L of LETTERS) {
        if (dict.isWord(up + L + down)) allowed.add(L);
      }
      let score = 0;
      for (const ch of up + down) score += letterValue(ch, false);
      cross[r][c] = { allowed, score, exists: true };
    }
  }
  return cross;
}

function computeAnchors(board: string[][]): boolean[][] {
  let anyTile = false;
  const anchors: boolean[][] = Array.from({ length: BOARD_SIZE }, () =>
    Array<boolean>(BOARD_SIZE).fill(false)
  );
  for (let r = 0; r < BOARD_SIZE; r++) {
    for (let c = 0; c < BOARD_SIZE; c++) {
      if (board[r][c] !== "") {
        anyTile = true;
        continue;
      }
      if (
        isFilled(board, r - 1, c) ||
        isFilled(board, r + 1, c) ||
        isFilled(board, r, c - 1) ||
        isFilled(board, r, c + 1)
      ) {
        anchors[r][c] = true;
      }
    }
  }
  if (!anyTile) anchors[CENTER][CENTER] = true; // first move plays through centre
  return anchors;
}

// Mutable rack represented as letter -> count, plus a blank count.
function buildRack(tiles: string[]): { counts: Map<string, number>; blanks: number } {
  const counts = new Map<string, number>();
  let blanks = 0;
  for (const t of tiles) {
    if (t === BLANK) blanks++;
    else counts.set(t, (counts.get(t) ?? 0) + 1);
  }
  return { counts, blanks };
}

function scoreMove(
  board: string[][],
  cross: CrossCheck[][],
  r: number,
  startCol: number,
  word: string,
  placements: Placement[]
): number {
  let wordMult = 1;
  let sum = 0;
  const placedByCol = new Map<number, Placement>();
  for (const p of placements) placedByCol.set(p.col, p);

  for (let i = 0; i < word.length; i++) {
    const col = startCol + i;
    const placed = placedByCol.get(col);
    if (placed) {
      const prem = premiumAt(r, col);
      sum += letterValue(placed.letter, placed.blank) * letterMultiplier(prem);
      wordMult *= wordMultiplier(prem);
    } else {
      sum += letterValue(board[r][col], false);
    }
  }
  let total = sum * wordMult;

  for (const p of placements) {
    const cc = cross[p.row][p.col];
    if (cc.exists) {
      const prem = premiumAt(p.row, p.col);
      const placedScore = letterValue(p.letter, p.blank) * letterMultiplier(prem);
      total += (cc.score + placedScore) * wordMultiplier(prem);
    }
  }

  if (placements.length === 7) total += 50; // bingo bonus
  return total;
}

function isConnected(
  board: string[][],
  placements: Placement[],
  word: string,
  r: number,
  startCol: number
): boolean {
  // A move is legal if it touches an existing tile: either the main word
  // includes a pre-existing tile, or a placed tile has a filled orthogonal
  // neighbour.
  for (let i = 0; i < word.length; i++) {
    if (board[r][startCol + i] !== "") return true;
  }
  for (const p of placements) {
    if (
      isFilled(board, p.row - 1, p.col) ||
      isFilled(board, p.row + 1, p.col) ||
      isFilled(board, p.row, p.col - 1) ||
      isFilled(board, p.row, p.col + 1)
    ) {
      return true;
    }
  }
  return false;
}

// Generates all horizontal plays for `board`. Coordinates are in the board's
// own orientation; the caller remaps for the transposed (vertical) pass.
function generateHorizontal(
  board: string[][],
  rackTiles: string[],
  dict: Dictionary
): Move[] {
  const moves: Move[] = [];
  const cross = computeCrossChecks(board, dict);
  const anchors = computeAnchors(board);
  const rack = buildRack(rackTiles);
  const firstMove = board.every((row) => row.every((c) => c === ""));

  const record = (r: number, startCol: number, word: string, placements: Placement[]) => {
    if (placements.length === 0 || word.length < 2) return;
    if (firstMove) {
      const coversCenter = placements.some(
        (p) => p.row === CENTER && p.col === CENTER
      );
      if (!coversCenter) return;
    } else if (!isConnected(board, placements, word, r, startCol)) {
      return;
    }
    moves.push({
      word,
      row: r,
      col: startCol,
      dir: "H",
      placements: placements.map((p) => ({ ...p })),
      score: scoreMove(board, cross, r, startCol, word, placements),
    });
  };

  const candidateLetters = (tile: string): string[] =>
    tile === BLANK ? LETTERS : [tile];

  const availableTiles = (): string[] => {
    const out: string[] = [];
    for (const [letter, count] of rack.counts) if (count > 0) out.push(letter);
    if (rack.blanks > 0) out.push(BLANK);
    return out;
  };

  const consume = (tile: string) => {
    if (tile === BLANK) rack.blanks--;
    else rack.counts.set(tile, (rack.counts.get(tile) ?? 0) - 1);
  };
  const restore = (tile: string) => {
    if (tile === BLANK) rack.blanks++;
    else rack.counts.set(tile, (rack.counts.get(tile) ?? 0) + 1);
  };

  const extendRight = (
    r: number,
    startCol: number,
    col: number,
    word: string,
    placements: Placement[]
  ) => {
    if (col >= BOARD_SIZE || board[r][col] === "") {
      if (dict.isWord(word)) record(r, startCol, word, placements);
      if (col >= BOARD_SIZE) return;
      const cc = cross[r][col];
      for (const tile of availableTiles()) {
        for (const L of candidateLetters(tile)) {
          if (cc.allowed !== null && !cc.allowed.has(L)) continue;
          const next = word + L;
          if (!dict.hasPrefix(next)) continue;
          consume(tile);
          placements.push({ row: r, col, letter: L, blank: tile === BLANK });
          extendRight(r, startCol, col + 1, next, placements);
          placements.pop();
          restore(tile);
        }
      }
    } else {
      const L = board[r][col];
      const next = word + L;
      if (dict.hasPrefix(next)) {
        extendRight(r, startCol, col + 1, next, placements);
      }
    }
  };

  const leftPart = (
    r: number,
    anchorCol: number,
    word: string,
    placements: Placement[],
    limit: number
  ) => {
    extendRight(r, anchorCol - word.length, anchorCol, word, placements);
    if (limit <= 0) return;
    const col = anchorCol - word.length - 1;
    if (col < 0) return;
    const cc = cross[r][col];
    for (const tile of availableTiles()) {
      for (const L of candidateLetters(tile)) {
        if (cc.allowed !== null && !cc.allowed.has(L)) continue;
        const next = L + word;
        if (!dict.hasPrefix(next)) continue;
        consume(tile);
        placements.unshift({ row: r, col, letter: L, blank: tile === BLANK });
        leftPart(r, anchorCol, next, placements, limit - 1);
        placements.shift();
        restore(tile);
      }
    }
  };

  for (let r = 0; r < BOARD_SIZE; r++) {
    for (let c = 0; c < BOARD_SIZE; c++) {
      if (!anchors[r][c]) continue;
      if (c > 0 && board[r][c - 1] !== "") {
        // Fixed prefix from existing tiles to the left.
        let k = c - 1;
        while (k >= 0 && board[r][k] !== "") k--;
        k++;
        const prefix = board[r].slice(k, c).join("");
        if (dict.hasPrefix(prefix)) {
          extendRight(r, k, c, prefix, []);
        }
      } else {
        // Count empty squares to the left until the previous anchor/tile/edge.
        let limit = 0;
        let k = c - 1;
        while (k >= 0 && board[r][k] === "" && !anchors[r][k]) {
          limit++;
          k--;
        }
        leftPart(r, c, "", [], limit);
      }
    }
  }

  return moves;
}

function transpose(board: string[][]): string[][] {
  const t: string[][] = Array.from({ length: BOARD_SIZE }, () =>
    Array<string>(BOARD_SIZE).fill("")
  );
  for (let r = 0; r < BOARD_SIZE; r++)
    for (let c = 0; c < BOARD_SIZE; c++) t[c][r] = board[r][c];
  return t;
}

function dedupe(moves: Move[]): Move[] {
  const best = new Map<string, Move>();
  for (const m of moves) {
    const sig =
      m.dir +
      "|" +
      m.placements
        .map((p) => `${p.row},${p.col},${p.letter}`)
        .sort()
        .join(";");
    const existing = best.get(sig);
    if (!existing || m.score > existing.score) best.set(sig, m);
  }
  return [...best.values()];
}

/**
 * Find the highest-scoring legal plays for `rackTiles` on `board`.
 * @param board 15x15 grid; "" for empty, single uppercase letter for a tile.
 * @param rackTiles up to 7 entries: "A".."Z" or "?" for a blank.
 * @param limit max number of plays to return (sorted best-first).
 */
export function findMoves(
  board: string[][],
  rackTiles: string[],
  dict: Dictionary,
  limit = 15
): Move[] {
  const tiles = rackTiles
    .map((t) => (t === BLANK ? BLANK : t.toUpperCase()))
    .filter((t) => t === BLANK || /^[A-Z]$/.test(t));

  const horizontal = generateHorizontal(board, tiles, dict);

  const transposed = transpose(board);
  const verticalRaw = generateHorizontal(transposed, tiles, dict);
  const vertical: Move[] = verticalRaw.map((m) => ({
    word: m.word,
    row: m.col, // remap transposed coords back to the real board
    col: m.row,
    dir: "V",
    placements: m.placements.map((p) => ({
      row: p.col,
      col: p.row,
      letter: p.letter,
      blank: p.blank,
    })),
    score: m.score,
  }));

  const all = dedupe([...horizontal, ...vertical]);
  all.sort((a, b) => b.score - a.score || a.word.localeCompare(b.word));
  return all.slice(0, limit);
}
