name: Deploy to GitHub Pages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, pages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
      - run: cp CNAME out/ || true      # keep your custom domain, if you have one
      - uses: actions/upload-pages-artifact@v2
        with: { path: ./out }
      - uses: actions/deploy-pages@v2
